modLoader="javafml"
loaderVersion="[43,)"
license="MPL 2.0"
issueTrackerURL="https://github.com/Tslat/TslatEffectsLib/issues"

[[mods]]
modId="tslateffectslib"
version="1.3"
displayName="Tslat EffectsLib"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for better mob effects
'''

[[dependencies.tslateffectslib]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.tslateffectslib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"
