modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Tslat/TslatEffectsLib/issues"

[[mods]]
modId="tslateffectslib"
version="1.5"
displayName="Tslat Effects Lib (TEL)"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for better mob effects
'''

[[dependencies.tslateffectslib]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"
[[dependencies.tslateffectslib]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
