modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/Tslat/TslatEffectsLib/issues"

[[mods]]
modId="tslateffectslib"
version="1.4.1"
displayName="Tslat EffectsLib"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for better mob effects
'''

[[dependencies.tslateffectslib]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"
[[dependencies.tslateffectslib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,)"
ordering="NONE"
side="BOTH"
