# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
group=net.tslat.effectslib
modDisplayName=TslatEffectsLib
modId=tslateffectslib
modAuthors=Tslat
modDescription=A library mod for better mob effects
modLicense=MIT
modHomepageUrl=https://www.curseforge.com/minecraft/mc-mods/tslateffectslib
modSourcesUrl=https://github.com/Tslat/TslatEffectsLib
modIssuesUrl=https://github.com/Tslat/TslatEffectsLib/issues

# Publishing
modCurseforgeId=700382
modModrinthId=7tc9Xfnw
modMavenUrl=https://maven.cloudsmith.io/tslat/tel/
modChangelogUrl=https://github.com/Tslat/TslatEffectsLib/commits/1.21.3