# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_name=TslatEffectsLib
group=net.tslat.effectslib
authors=Tslat
mod_id=tslateffectslib
description=A library mod for better mob effects
license=MIT
mappings_channel=parchment
homepage_url=https://www.curseforge.com/minecraft/mc-mods/tslateffectslib
sources_url=https://github.com/Tslat/TslatEffectsLib
issues_url=https://github.com/Tslat/TslatEffectsLib/issues

# Common Versions
version=1.9.2
parchment_version=2024.06.23
mappings_mc_version=1.21
minecraft_version=1.21
minecraft_version_range=[1.21,)
java_version=21
mixin_processor_version=0.8.6

# Forge
forge_version=51.0.21
forge_version_range=[51.0.0,)
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.60-beta
neoforge_version_range=[21.0.60-beta,)
neoforge_loader_version_range=[4,)

# Fabric
fabric_api_version=0.100.4+1.21
fabric_loader_version=0.15.11

# Dependencies
mixinextras_version=0.3.6

# Publishing
curseforge_id=700382
maven_url=https://maven.cloudsmith.io/tslat/tel/
changelog_url=https://github.com/Tslat/TslatEffectsLib/commits/1.21