modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MIT"
issueTrackerURL="https://github.com/Tslat/TslatEffectsLib/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="Tslat Effects Lib (TEL)"
    logoFile="logo.png"
    authors="Tslat"
    displayTest="IGNORE_SERVER_VERSION"
    description='''
A library mod for better mob effects
'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
